package consts

const (
	MPESA_FLOAT = "MPESA_FLOAT"

	CASH_WITHDRAW = "CASH_WITHDRAW"

	FLOAT_PURCHASE = "FLOAT_PURCHASE"
	FLOAT_TRANSFER = "FLOAT_TRANSFER"
	FLOAT_WITHDRAW = "FLOAT_WITHDRAW"

	EARNINGS_WITHDRAW = "EARNINGS_WITHDRAW"
)
